from __future__ import annotations

from freight_second_brain.warehouse.schemas import AccessStatus, CatalogSource, HistoricalAvailability

SOURCE_CATALOG: list[CatalogSource] = [
    CatalogSource(
        source_id="baltic_exchange",
        name="Baltic Exchange Dry Services",
        publisher="Baltic Exchange",
        source_type="methodology",
        status=AccessStatus.VERIFIED_PARTIAL,
        data_and_purpose="Primary dry-bulk benchmark definitions, route codes and vessel assumptions.",
        access_pattern="Public HTML methodology; licensed history.",
        default_url="https://www.balticexchange.com/en/data-services/market-information0/dry-services.html",
        license="Baltic Exchange terms; methodology pages public",
        historical_available=HistoricalAvailability.PARTIAL,
        history_frequency="methodology versions",
        history_access_method="html_snapshot",
        history_requires_license=True,
        fallback_source_ids=["mendeley_bdi", "trading_economics_bdi"],
        extractor="qualitative_pages",
        notes="Do not treat HTML snapshots as numerical history.",
    ),
    CatalogSource(
        source_id="mendeley_bdi",
        name="Mendeley BDI sub-index workbook",
        publisher="Mendeley Data / Totakura",
        source_type="freight_index",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Reproducible daily BCI/BPI/BSI/BHSI history 2012-08-01 to 2019-07-31.",
        access_pattern="Public dataset API + XLS download, CC BY 4.0.",
        default_url="https://data.mendeley.com/datasets/t76ckh2ygg/1",
        license="CC BY 4.0",
        historical_available=HistoricalAvailability.YES,
        history_start="2012-08-01",
        history_end="2019-07-31",
        history_frequency="daily",
        history_access_method="public_api_file",
        history_revision_behavior="fixed_sample",
        extractor="mendeley_bdi",
        notes="Historical benchmark only; not a current Baltic feed.",
    ),
    CatalogSource(
        source_id="trading_economics_bdi",
        name="Trading Economics Baltic Dry",
        publisher="Trading Economics",
        source_type="freight_index",
        status=AccessStatus.FALLBACK,
        data_and_purpose="Secondary current BDI level for prototype monitoring.",
        access_pattern="Public market page snapshot; paid API for history.",
        default_url="https://tradingeconomics.com/commodity/baltic",
        license="Trading Economics terms; snapshot of publicly displayed last value",
        historical_available=HistoricalAvailability.PARTIAL,
        history_frequency="daily",
        history_access_method="html_snapshot",
        fallback_source_ids=["mendeley_bdi"],
        extractor="trading_economics_bdi",
        notes="Store only the displayed last value plus page snapshot. Not a licensed Baltic series.",
    ),
    CatalogSource(
        source_id="yahoo_finance",
        name="Yahoo Finance market proxies",
        publisher="Yahoo Finance",
        source_type="financial",
        status=AccessStatus.FALLBACK,
        data_and_purpose="Public financial proxies: BDRY ETF, energy/metals/grains futures, FX, VIX.",
        access_pattern="Chart API JSON.",
        default_url="https://query1.finance.yahoo.com/v8/finance/chart/",
        license="Yahoo terms; cache raw responses; prefer exchange data in production",
        historical_available=HistoricalAvailability.YES,
        history_frequency="daily",
        history_access_method="chart_api",
        extractor="yahoo_finance",
        notes="BDRY is an ETF proxy, not the BDI.",
    ),
    CatalogSource(
        source_id="world_bank_pink_sheet",
        name="World Bank Pink Sheet",
        publisher="World Bank Prospects Group",
        source_type="commodity_price",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Monthly commodity prices including coal, iron ore, grains, fertilizers, energy.",
        access_pattern="Official monthly XLSX.",
        default_url="https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Historical-Data-Monthly.xlsx",
        license="World Bank terms of use",
        historical_available=HistoricalAvailability.YES,
        history_start="1960-01",
        history_frequency="monthly",
        history_access_method="xlsx",
        history_revision_behavior="revised_in_place_archive_each_release",
        extractor="world_bank_pink_sheet",
    ),
    CatalogSource(
        source_id="world_bank_api",
        name="World Bank Data API",
        publisher="World Bank",
        source_type="macro",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="GDP, trade and industrial-demand country indicators.",
        access_pattern="REST JSON v2.",
        default_url="https://api.worldbank.org/v2/",
        license="CC BY 4.0",
        historical_available=HistoricalAvailability.YES,
        history_frequency="annual",
        history_access_method="api",
        extractor="world_bank_api",
    ),
    CatalogSource(
        source_id="imf_pcps",
        name="IMF Primary Commodity Prices",
        publisher="IMF",
        source_type="commodity_price",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Monthly international commodity prices; cross-check for Pink Sheet.",
        access_pattern="Excel database from IMF research page.",
        default_url="https://www.imf.org/en/research/commodity-prices",
        license="IMF terms",
        historical_available=HistoricalAvailability.YES,
        history_frequency="monthly",
        history_access_method="xlsx",
        fallback_source_ids=["world_bank_pink_sheet"],
        extractor="imf_pcps",
        enabled_by_default=False,
        notes="Host often returns 403 to automated clients; Pink Sheet is the fallback.",
    ),
    CatalogSource(
        source_id="fao_fpi",
        name="FAO Food Price Index",
        publisher="FAO",
        source_type="commodity_price",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Monthly cereal and food-price indices from 1990.",
        access_pattern="Stable CSV.",
        default_url="https://www.fao.org/media/docs/worldfoodsituationlibraries/default-document-library/food_price_indices_data.csv",
        license="FAO / CC BY-compatible public statistics",
        historical_available=HistoricalAvailability.YES,
        history_start="1990-01",
        history_frequency="monthly",
        history_access_method="csv",
        extractor="fao_fpi",
    ),
    CatalogSource(
        source_id="usda_psd",
        name="USDA FAS PSD",
        publisher="USDA FAS",
        source_type="supply_demand",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Grain and oilseed production, trade, consumption and stocks.",
        access_pattern="Public ZIP/CSV bulk files.",
        default_url="https://apps.fas.usda.gov/psdonline/downloads/psd_grains_pulses_csv.zip",
        license="US public domain",
        historical_available=HistoricalAvailability.YES,
        history_frequency="annual_market_year_with_monthly_vintages",
        history_access_method="zip_csv",
        history_revision_behavior="revised_vintages",
        extractor="usda_psd",
    ),
    CatalogSource(
        source_id="comtrade",
        name="UN Comtrade preview API",
        publisher="UN Statistics Division",
        source_type="trade",
        status=AccessStatus.VERIFIED_PARTIAL,
        data_and_purpose="Annual bilateral dry-bulk commodity flows (iron ore, coal, grains, bauxite).",
        access_pattern="Public preview REST JSON; throttled; 500-row cap.",
        default_url="https://comtradeapi.un.org/public/v1/preview/C/A/HS",
        license="UN Comtrade terms",
        historical_available=HistoricalAvailability.YES,
        history_frequency="annual_preview",
        history_access_method="api",
        extractor="comtrade",
        notes="Preview is not a complete monthly panel.",
    ),
    CatalogSource(
        source_id="data360_maritime",
        name="World Bank Data360 UNCTAD Maritime Transport",
        publisher="UNCTAD / World Bank Data360",
        source_type="fleet_ports",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Port calls, time in port, vessel age/size/capacity and seaborne trade indicators.",
        access_pattern="Data360 REST JSON.",
        default_url="https://data360api.worldbank.org/data360/data?DATABASE_ID=UNCTAD_MT",
        license="World Bank / UNCTAD public statistics",
        historical_available=HistoricalAvailability.YES,
        history_start="2010",
        history_end="2023",
        history_frequency="annual",
        history_access_method="api",
        extractor="data360_maritime",
    ),
    CatalogSource(
        source_id="eia_coal",
        name="EIA coal bulk dataset",
        publisher="U.S. EIA",
        source_type="energy",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="US coal production, trade, prices and stocks as bulk NDJSON.",
        access_pattern="Keyless bulk ZIP; APIv2 requires a free key.",
        default_url="https://www.eia.gov/opendata/bulk/COAL.zip",
        license="US public domain",
        historical_available=HistoricalAvailability.YES,
        history_frequency="mixed",
        history_access_method="bulk_zip",
        extractor="eia_coal",
    ),
    CatalogSource(
        source_id="fred",
        name="FRED macro series",
        publisher="Federal Reserve Bank of St. Louis",
        source_type="macro",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="WTI, industrial production, FX, VIX and related macro drivers.",
        access_pattern="CSV/API; API key optional for some endpoints.",
        default_url="https://fred.stlouisfed.org/graph/fredgraph.csv",
        license="FRED terms",
        historical_available=HistoricalAvailability.YES,
        history_frequency="mixed",
        history_access_method="csv",
        fallback_source_ids=["yahoo_finance", "world_bank_api"],
        extractor="fred",
        enabled_by_default=False,
        notes="This environment has seen timeouts; Yahoo/World Bank cover the same drivers.",
    ),
    CatalogSource(
        source_id="noaa_enso",
        name="NOAA CPC Oceanic Niño Index",
        publisher="NOAA CPC",
        source_type="weather",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Seasonal ENSO state as a grain/weather regime feature.",
        access_pattern="Public ASCII index file.",
        default_url="https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt",
        license="US public domain",
        historical_available=HistoricalAvailability.YES,
        history_start="1950",
        history_frequency="monthly_seasonal",
        history_access_method="ascii",
        extractor="noaa_enso",
    ),
    CatalogSource(
        source_id="hellenic_rss",
        name="Hellenic Shipping News dry-bulk RSS",
        publisher="Hellenic Shipping News",
        source_type="news",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Dated dry-bulk market news and BDI composite headlines. Warehouse stores a feed snapshot; live desk uses press_fetch; harness uses rss_feed.",
        access_pattern="RSS 2.0.",
        default_url="https://www.hellenicshippingnews.com/category/shipping-news/dry-bulk-market/feed/",
        license="Publisher terms; store metadata and permitted excerpts",
        historical_available=HistoricalAvailability.YES,
        history_frequency="intraday_to_daily",
        history_access_method="rss",
        extractor="hellenic_rss",
    ),
    CatalogSource(
        source_id="bimco",
        name="BIMCO market analysis",
        publisher="BIMCO",
        source_type="research",
        status=AccessStatus.VERIFIED_PARTIAL,
        data_and_purpose="Public dry-bulk outlook pages and weekly statistics summaries.",
        access_pattern="Public HTML; full reports often members-only.",
        default_url="https://www.bimco.org/news-insights/market-analysis/",
        license="BIMCO terms; public pages only",
        historical_available=HistoricalAvailability.PARTIAL,
        history_access_method="html_snapshot",
        extractor="qualitative_pages",
    ),
    CatalogSource(
        source_id="unctad_rmt",
        name="UNCTAD Review of Maritime Transport 2025",
        publisher="UNCTAD",
        source_type="research",
        status=AccessStatus.VERIFIED_PUBLIC,
        data_and_purpose="Annual fleet, trade, dry-bulk rate and supply/demand narrative.",
        access_pattern="Direct PDF.",
        default_url="https://unctad.org/system/files/official-document/rmt2025_en.pdf",
        license="UNCTAD publication terms",
        historical_available=HistoricalAvailability.YES,
        history_frequency="annual",
        history_access_method="pdf",
        extractor="qualitative_pages",
    ),
    CatalogSource(
        source_id="gdelt",
        name="GDELT DOC API",
        publisher="GDELT Project",
        source_type="news_discovery",
        status=AccessStatus.FALLBACK,
        data_and_purpose="News discovery metadata for dry-bulk, iron ore, coal and grain events.",
        access_pattern="Public DOC API JSON; rate-limited.",
        default_url="https://api.gdeltproject.org/api/v2/doc/doc",
        license="GDELT terms; metadata only",
        historical_available=HistoricalAvailability.YES,
        history_access_method="api",
        extractor="gdelt",
        enabled_by_default=False,
        notes="Discovery layer only; confirm headlines on primary sources.",
    ),
]


def get_source(source_id: str) -> CatalogSource:
    for source in SOURCE_CATALOG:
        if source.source_id == source_id:
            return source
    raise KeyError(source_id)


def list_enabled_extractors() -> list[str]:
    names: list[str] = []
    for source in SOURCE_CATALOG:
        if source.enabled_by_default and source.extractor and source.extractor not in names:
            names.append(source.extractor)
    return names
